Add support for reading and writing <volume> tags
scalableminds/wknml pull request #41
Opened 2020-12-10 16:52 UTC by hotzenklotz

## Changes
- PR adds supports for reading and writing volume tags from NML files:
```
<volume id="1" location="data.zip" fallbackLayer="segmentation" />
```
- extended type annotations

## Issues
Fixes #34

2020-12-14 15:20 UTC, daniel-wer requested changes
The `<volume>` tag support looks very good to me. Thanks a lot for your work documenting the missing modules! I only noticed too late that I made all my suggestions for the generated docs instead of the source files, so you need to transfer my suggestions manually, sorry for that :disappointed:

2020-12-14 15:20 UTC, daniel-wer commented on docs/wknml.md
> +- `group_dict` _Dict[str, List[nx.Graph]]_ - A mapping of group names to a list of tree as NetworkX graph objects
```suggestion
- `group_dict` _Dict[str, List[nx.Graph]]_ - A mapping of group names to a list of trees as NetworkX graph objects
```

2020-12-14 15:20 UTC, daniel-wer commented on docs/wknml.md
> +Note: Does not update any `Comment`s or `BranchPoint`s referencing these nodes.
In this state (where the trees are nx.Graphs), branchpoints and comments are indicated by a `branchpoint` or `comment` attribute at the respective node, so there is no need to update any IDs. The separate branchpoints and comments lists are only generated from the nx.Graphs, later.

2020-12-14 15:20 UTC, daniel-wer commented on docs/wknml.md
> +- `group_dict` _Dict[str, List[nx.Graph]]_ - A mapping of group names to a list of tree as NetworkX graph objects
```suggestion
- `group_dict` _Dict[str, List[nx.Graph]]_ - A mapping of group names to a list of trees as NetworkX graph objects
```

2020-12-14 15:20 UTC, daniel-wer commented on docs/wknml.md
> +- `tree_dict` _Union[List[nx.Graph], Dict[str, List[nx.Graph]]]_ - A list of wK tree-like structures as NetworkX graphs or a dictionary of group names and same list of NetworkX tree objects.
```suggestion
- `tree_dict` _Union[List[nx.Graph], Dict[str, List[nx.Graph]]]_ - A list of wK tree-like structures as NetworkX graphs or a dictionary of group names and lists of NetworkX tree objects.
```

2020-12-14 15:20 UTC, daniel-wer commented on docs/wknml.md
> +- `volume` _Optional[Dict[str, Any]] = None_ - A dictionary representation of a reference to wK a volume annotation. See `Volume` object for attributes.
```suggestion
- `volume` _Optional[Dict[str, Any]] = None_ - A dictionary representation of a reference to a wK volume annotation. See `Volume` object for attributes.
```

2020-12-14 15:20 UTC, daniel-wer commented on docs/wknml.md
> +  2. A dictionary representation of the NML metadata parameters
```suggestion
```

Looks like this is a leftover as these are not returned by `generate_nml`.

2020-12-14 15:20 UTC, daniel-wer commented on docs/wknml.md
> +A utility to convert wK NML object into a [NetworkX graph object](https://networkx.org/). Skeletons/Trees are grouped by the provided groups in the NML file.
```suggestion
A utility to convert a wK NML object into a [NetworkX graph object](https://networkx.org/). Skeletons/Trees are grouped by the provided groups in the NML file.
```

2020-12-14 15:20 UTC, daniel-wer commented on docs/wknml.md
> +A utility to convert a single [NetworkX graph object](https://networkx.org/) into a list of `Node`objects and `Edge` objects.
```suggestion
A utility to convert a single [NetworkX graph object](https://networkx.org/) into a list of `Node` objects and `Edge` objects.
```

2020-12-14 15:20 UTC, daniel-wer commented on docs/wknml.md
> +    Tuple[List[Node], List[Edge]]: A tuple contain both all nodes and edges
```suggestion
    Tuple[List[Node], List[Edge]]: A tuple containing all nodes and all edges
```

2020-12-14 15:20 UTC, daniel-wer commented on tests/test_nml_objects.py
> +
```suggestion
```

Looks like a superfluous auto-import

2020-12-15 12:39 UTC, hotzenklotz commented on docs/wknml.md
> +  Setting a task or user bounding boxes will cause wK to 1) render these visually and 2) prevent data loading from outside them.
Well, it already is super wK-specific is it not? Tasks are very wK. NMLs are very wK.

2020-12-15 13:01 UTC, daniel-wer commented on docs/wknml.md
> +  Setting a task or user bounding boxes will cause wK to 1) render these visually and 2) prevent data loading from outside them.
Yes, I see your point. I just wasn't sure whether this information could be better suited for the wK tasks documentation. I don't have a strong opinion on this, your call.

2020-12-15 13:06 UTC, daniel-wer commented
@hotzenklotz Just to make sure that you see all the feedback I gave - I had to click "Load More"  to see all comments as there were "hidden conversations".

2020-12-15 14:06 UTC, merged

2020-12-15 14:29 UTC, hotzenklotz commented on docs/wknml.md
> +- `scale` _Vector3_ - Voxel scale of the referenced dataset in nanometers.
Yes, it would be great to automatically document/export the custom type definition as well.